# Generated by Django 4.2.6 on 2024-02-10 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crazy8Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crazy8Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HMW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sdgs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crazy8stack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.crazy8stack')),
                ('hmw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.hmw')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.problem')),
            ],
        ),
    ]
