# Generated by Django 4.2.6 on 2024-02-08 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sketches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hmw',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmws', to='sketches.problem'),
        ),
        migrations.AddField(
            model_name='crazy8stack',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crazy8stacks', to='sketches.problem'),
        ),
        migrations.AddField(
            model_name='crazy8content',
            name='crazy8stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='sketches.crazy8stack'),
        ),
    ]
