# Generated by Django 4.2.6 on 2024-02-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_crazy8content_created_at_crazy8stack_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='crazy8stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.crazy8stack'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='hmw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.hmw'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', to='sketches.problem'),
        ),
    ]
