# Generated by Django 4.2.6 on 2024-02-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sketches', '0003_remove_crazy8content_user_remove_crazy8stack_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to=settings.AUTH_USER_MODEL),
        ),
    ]
