# Generated by Django 4.2.6 on 2024-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='writer',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
