# Generated by Django 4.2.6 on 2024-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='writer',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
    ]
