# Generated by Django 4.2.6 on 2024-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
