# Generated by Django 4.2.6 on 2024-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_title_alter_issue_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuelist',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
