# Generated by Django 4.2.6 on 2024-02-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issuelist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
