# Generated by Django 4.2.6 on 2024-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_image_url_alter_issuelist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelist',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
