# Generated by Django 4.2.6 on 2024-02-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issuelist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='article_id',
            field=models.CharField(blank=True, default='unknown', max_length=500, null=True),
        ),
    ]
