# Generated by Django 4.2.6 on 2024-02-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
