# Generated by Django 4.2.6 on 2024-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
