# Generated by Django 4.2.6 on 2024-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_additional_info_provided_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_impact',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='post_total',
            field=models.IntegerField(default=0),
        ),
    ]
